CREATE TABLE INSTRUCTOR (INS_ID INT PRIMARY KEY NOT NULL, LASTNAME VARCHAR(100), FIRSTNAME VARCHAR(100), CITY VARCHAR(100), COUNTRY VARCHAR(100));

INSERT INTO INSTRUCTOR (INS_ID, LASTNAME, FIRSTNAME, CITY, COUNTRY) VALUES (001, 'NEVES', 'GILMAR', 'SAO PAULO', 'BR');

INSERT INTO INSTRUCTOR (INS_ID, LASTNAME, FIRSTNAME, CITY, COUNTRY) VALUES (002, 'LOPES', 'KAREN', 'BELEM', 'BR'), (0023, 'SIMPSOM', 'HOMER', 'SPRINGFIELD', 'US');

UPDATE INSTRUCTOR SET INS_ID = 003 WHERE FIRSTNAME = 'HOMER' ;

SELECT * FROM INSTRUCTOR;
